[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
[block.format]
full = " $title |"
short = " $title.str(max_w:50) |"

[[block]]
block = "custom"
command = " pgrep wf-recorder > /dev/null && echo "
hide_when_empty = true

[[block]]
block = "custom"
command = " sed 's/  //' <(curl 'https://wttr.in/jamal+patna?format='%t+%w+%p'' -sf) "
interval = 600

[[block]]
block = "time"
interval = 1
timezone = ["Asia/Kolkata", "Asia/Tokyo"]
format = " $timestamp.datetime(f:'%a, %d %b. %r %Z') "
[[block.click]]
button = "right"
cmd = "zenity --calendar --text=Calendar"

[[block]]
block = "kdeconnect"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:4,u:B,p:M) "
format_alt = " $icon_swap $swap_used.eng(w:4,u:B,p:M) "

[[block]]
block = "cpu"

[[block]]
block = "temperature"
format = " $icon $average "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "coretemp-isa-0000"

[[block]]
block = "net"

[[block]]
block = "custom"
command = "printf '%s' $(makoctl mode | grep -q 'dnd' && echo dnd || echo default)"
signal = 11
[[block.click]]
button = "left"
cmd = "makoctl mode | grep 'dnd' && makoctl mode -r dnd || makoctl mode -a dnd; pkill -RTMIN+11 i3status-rs"
[[button.click]]
button = "right"
cmd = "makoctl restore"

